stages:
  - update

update_flake_inputs:
  stage: update
  tags:
    - nix shell
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - git config --global user.name 'Renovate Bot'
    - git config --global user.email 'gitlab-renovate@blahai.gay'
    - nix flake update --commit-lock-file
    - nix run .#update
    - git push origin main