default:
  tags:
    - nix

stages:
  - update
  - build

update_flake_inputs:
  stage: update
  tags:
    - nix 
  before_script:
    - git config --global user.name "haibot"
    - git config --global user.email "haibot@blahai.gay"
    - git remote set-url --push origin "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  script:
    - nix flake update --commit-lock-file
    - nix run .#update
    - git push origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

build_packages:
  stage: build
  tags:
    - shell
    - nix
  script:
    - |
      nix run nixpkgs#nix-fast-build -- \
        --no-nom \
        --skip-cached \
        --systems x86_64-linux \
        --option accept-flake-config true \
        --flake .#hydraJobs.x86_64-linux \
        --cachix-cache haipkgs
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - pkgs/**
      when: always
    - when: never
  variables:
    CACHIX_SIGNING_KEY: $CACHIX_SIGNING_KEY
    CACHIX_AUTH_TOKEN: $CACHIX_AUTH_TOKEN