name: Build & cache packages

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Bump Flake Inputs
    types:
      - completed
  push:
    paths:
      - pkgs/

jobs:
  build:
    name: build
    runs-on: lix-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cachix
        run: |
          nix profile install github:cachix/cachix/latest --accept-flake-config

      - name: Build packages
        env:
          CACHIX_SIGNING_KEY: "${{ secrets.CACHIX_SIGNING_KEY }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        run: |
          nix run \
            github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --systems x86_64-linux \
            --option accept-flake-config true \
            --flake .#hydraJobs.x86_64-linux \
            --cachix-cache haipkgs
