name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: Theia

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: haipkgs
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Build from the matrix
        run: |
          nix run \
            github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --systems x86_64-linux \
            --option accept-flake-config true \
            --flake .#hydraJobs.x86_64-linux
