name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: lix-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name 'Renovate Bot'
          git config --global user.email 'forgejo-renovate-action@forgejo.org'

      - name: Update Lockfile
        run: nix flake update --commit-lock-file

      - name: Update Packages
        run: nix run .#update

      - name: Push changes
        run: git push origin main
