name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: https://github.com/DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update Lockfile
        run: nix flake update --commit-lock-file

      - name: Update Packages
        run: nix run .#update --option accept-flake-config true

      - name: Push changes
        run: git push origin main
